# Generated by Django 5.1.2 on 2025-04-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='pictures/')),
                ('datePublished', models.DateTimeField(verbose_name='date published')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
                ('birthDate', models.DateField()),
                ('biography', models.CharField(max_length=100)),
                ('joindate', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, to='hubspace.profile')),
                ('following', models.ManyToManyField(blank=True, to='hubspace.profile')),
                ('profilePicture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hubspace.picture')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('datepublished', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubspace.profile')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubspace.profile'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('timeSent', models.DateTimeField(verbose_name='date published')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_messages', to='hubspace.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='hubspace.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubspace.post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubspace.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('datepublished', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hubspace.post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubspace.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='hubspace.profile')),
            ],
        ),
    ]
