# Generated by Django 5.1.2 on 2025-04-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0002_remove_profile_following_alter_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='hubspace.profile'),
        ),
    ]
