# Generated by Django 5.1.2 on 2025-04-12 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0005_rename_sender_message_author_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='hubspace.profile'),
        ),
    ]
