# Generated by Django 5.1.2 on 2025-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0006_alter_picture_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='datePublished',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
