# Generated by Django 5.1.2 on 2025-04-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0008_page_picture_page_post_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubspace.page'),
        ),
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubspace.page'),
        ),
    ]
