# Generated by Django 5.1.2 on 2025-04-22 11:53

import django.db.models.deletion
import hubspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0009_alter_picture_page_alter_post_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timeSent',
            new_name='datePublished',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datepublished',
            new_name='datePublished',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='author',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='page',
        ),
        migrations.AddField(
            model_name='picture',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubspace.post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePicture',
            field=models.ForeignKey(blank=True, default=hubspace.models.get_default_picture, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hubspace.picture'),
        ),
    ]
