# Generated by Django 5.1.2 on 2025-04-22 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0010_rename_timesent_message_datepublished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hubspace.profile'),
        ),
    ]
