# Generated by Django 5.1.2 on 2025-04-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspace', '0013_alter_picture_author_alter_picture_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='hubspace.post'),
        ),
    ]
